<a href="https://colab.research.google.com/github/rix7kz/AI-ML/blob/main/Lecture_71.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#pandas

In [11]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.2.3'

In [4]:
students=pd.DataFrame({
    "Name":["akash","deepanshu","rishu","rishi"],
    "marks":[30,40,60,50]
})
print(students)

        Name  marks
0      akash     30
1  deepanshu     40
2      rishu     60
3      rishi     50

In [5]:
students

        Name  marks
0      akash     30
1  deepanshu     40
2      rishu     60
3      rishi     50

In [8]:
#series
marks = pd.Series([80,90,30,40,50])
print(marks)

0    80
1    90
2    30
3    40
4    50
dtype: int64

In [9]:
data = pd.Series(
    [100,200,300,400,500],
    index = ["jan","feb","mar","april","may"]

    )
data

jan      100
feb      200
mar      300
april    400
may      500
dtype: int64

In [12]:
#create a panda series using a numpy array
arr = np.array([80,70,60,50,40])
num = pd.Series(arr)
print(num)

0    80
1    70
2    60
3    50
4    40
dtype: int64

In [14]:
num = num + 5
print(num)

0    90
1    80
2    70
3    60
4    50
dtype: int64